### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by pavelmickevic** [Graitavicius/userList#1]
Hello, sadly you did not create a pull request to `main` branch, so I can make some comments on specific lines

will post it here instead:

--- 

https://github.com/Graitavicius/userList/compare/main@%7B7day%7D...main

**Comment by pavelmickevic** [comment]
please read the docs since you're using `createSlice` utility

https://github.com/Graitavicius/userList/blob/92b3b43b0a216dcc0a16f0059efbe0e7e2f2d0c3/src/store/table-slice.js#L13

https://redux-toolkit.js.org/usage/immer-reducers

Look how the add elements to array. Not using `...spreads`

**Comment by pavelmickevic** [comment]
why did you do this tranformation? `toJSON` the `fromJSON` ? 

https://github.com/Graitavicius/userList/blob/92b3b43b0a216dcc0a16f0059efbe0e7e2f2d0c3/src/App.js#L29-L30

**Comment by pavelmickevic** [comment]
pretty weird pattern (at least to me)

https://github.com/Graitavicius/userList/blob/92b3b43b0a216dcc0a16f0059efbe0e7e2f2d0c3/src/components/filters/DateRange.js#L14-L15

I mean, the `setStartDateExists` flag. 

--- 

https://github.com/Graitavicius/userList/blob/92b3b43b0a216dcc0a16f0059efbe0e7e2f2d0c3/src/components/filters/DateRange.js#L29

`htmlFor` - very good. I love it ❤️ 
Be sure to know why this is important attribute in a modern world

**Comment by pavelmickevic** [comment]
https://github.com/Graitavicius/userList/blob/92b3b43b0a216dcc0a16f0059efbe0e7e2f2d0c3/src/components/filters/DateRange.js#L14

why did you use a format string `.format("M/D/yyyy")` ? 

to me it works without it

```
moment('9/19/2017').format()
// '2017-09-19T00:00:00+03:00'
```

**Comment by pavelmickevic** [comment]
OOoooo man :)

https://github.com/Graitavicius/userList/blob/92b3b43b0a216dcc0a16f0059efbe0e7e2f2d0c3/src/components/users/UserTable.js#L60-L70

you already used `moment` lib in other files. You can use it here for dates here too.

consider following
```diff
-.split('/').join('-')
+moment(startDate).format('YYYY-MM-DD')
```

```diff
-if (rangeStartObj.getTime() <= startDateUsersObj.getTime()) {
+if (moment(startDateUsers).isBefore( moment(rangeStartObj ) {
```

please read about moment's utilities, like `isBefore` is `isAfter`

**Comment by pavelmickevic** [comment]
Hey, what is this? Why do you need a random? This is horrible 🙈 , absolute anti-pattern 🥇 

https://github.com/Graitavicius/userList/blob/92b3b43b0a216dcc0a16f0059efbe0e7e2f2d0c3/src/components/users/UserTable.js#L119

please read https://reactjs.org/docs/lists-and-keys.html#keys 

specifically quote: 
> The best way to pick a key is to use a string that uniquely identifies a list item among its siblings. Most often you would use IDs from your data as keys:

**Comment by Graitavicius** [comment]
Thank you for the feedback, appreciate that a lot.
So the question is, am I supposed to improve my code in this app or wait for further instructions via email?

**Comment by pavelmickevic** [comment]
Just keep it as it is now, 
but anyway please read the links I shared here. 

Please wait for further emails.
